### ISSUE TITLE
People - 'Remote Call' option breaks

### ISSUE THREAD

**Issue by SwenSchaeferjohann** [upframe/upframe.io#91] opened 2019-01-18 20:52 UTC
<img width="415" alt="issue001" src="https://user-images.githubusercontent.com/42959314/51412198-13412d80-1b6b-11e9-83e8-23b8e03b1bda.png">
""

**Comment by SwenSchaeferjohann** [comment] 2019-01-18 21:04
Cannot successfully request "remote-call".

**Comment by ulissesferreira** [comment] 2019-01-18 21:46
Just commited code that fixes that. Gonna test then close

**Comment by ulissesferreira** [comment] 2019-01-18 21:50
Just confirmed that the problem is fixed. The meetup location will be the room of the talk. Powered by talky.io. Closing

**Closed as completed** 2019-01-18 21:50 UTC
